/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef BYNACAM_INJECTOR_PRIVATE_H
#define BYNACAM_INJECTOR_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.2.0.0"
#define VER_MAJOR	1
#define VER_MINOR	2
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	"beziak"
#define FILE_VERSION	"v1.2"
#define FILE_DESCRIPTION	"BynaCam DLL Injector"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"bynacam.exe"
#define PRODUCT_NAME	"DLL Injector"
#define PRODUCT_VERSION	"v1.2"

#endif /*BYNACAM_INJECTOR_PRIVATE_H*/
